[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ebook-flashcards"
version = "0.1.0"
dependencies = [
    "google-generativeai",
    "jieba",
    "pandas",
    "pytest",
]

[tool.setuptools.packages.find]
where = ["src"]
